//! Generates `internal/unicode/tables.mbt` from Rust's own Unicode data so that
//! the MoonBit port classifies and case-maps characters exactly like upstream
//! typify (which relies on `char` methods, `heck`, and `unicode-ident`).

use std::fmt::Write;

fn ranges(pred: impl Fn(char) -> bool) -> Vec<(u32, u32)> {
    let mut out: Vec<(u32, u32)> = Vec::new();
    for cp in 0..=0x10FFFFu32 {
        let Some(c) = char::from_u32(cp) else { continue };
        if !pred(c) {
            continue;
        }
        match out.last_mut() {
            Some((_, hi)) if *hi + 1 == cp => *hi = cp,
            // Skip over the surrogate gap so ranges stay maximal.
            Some((_, hi)) if *hi == 0xD7FF && cp == 0xE000 => *hi = cp,
            _ => out.push((cp, cp)),
        }
    }
    out
}

fn emit_ranges(out: &mut String, name: &str, doc: &str, rs: &[(u32, u32)]) {
    writeln!(out, "///|\n/// {doc}\n/// Flattened inclusive `[lo, hi]` pairs, sorted.").unwrap();
    writeln!(out, "let {name} : ReadOnlyArray[Int] = [").unwrap();
    for chunk in rs.chunks(6) {
        let line: Vec<String> = chunk
            .iter()
            .map(|(lo, hi)| format!("0x{lo:X}, 0x{hi:X}"))
            .collect();
        writeln!(out, "  {},", line.join(", ")).unwrap();
    }
    writeln!(out, "]\n").unwrap();
}

fn emit_mapping(out: &mut String, name: &str, doc: &str, f: impl Fn(char) -> String) {
    let mut keys = Vec::new();
    let mut vals = Vec::new();
    for cp in 0..=0x10FFFFu32 {
        let Some(c) = char::from_u32(cp) else { continue };
        let m = f(c);
        if m != c.to_string() {
            keys.push(cp);
            vals.push(m);
        }
    }
    writeln!(out, "///|\n/// {doc} (keys)").unwrap();
    writeln!(out, "let {name}_keys : ReadOnlyArray[Int] = [").unwrap();
    for chunk in keys.chunks(10) {
        let line: Vec<String> = chunk.iter().map(|k| format!("0x{k:X}")).collect();
        writeln!(out, "  {},", line.join(", ")).unwrap();
    }
    writeln!(out, "]\n").unwrap();
    writeln!(out, "///|\n/// {doc} (values, parallel to keys)").unwrap();
    writeln!(out, "let {name}_values : ReadOnlyArray[String] = [").unwrap();
    for chunk in vals.chunks(8) {
        let line: Vec<String> = chunk
            .iter()
            .map(|v| {
                let esc: String = v.chars().map(|c| format!("\\u{{{:X}}}", c as u32)).collect();
                format!("\"{esc}\"")
            })
            .collect();
        writeln!(out, "  {},", line.join(", ")).unwrap();
    }
    writeln!(out, "]\n").unwrap();
}

fn main() {
    let mut out = String::new();
    writeln!(
        out,
        "// Code generated by scripts/gen-unicode.sh; DO NOT EDIT.\n// Source: `char` methods of {} and unicode-ident 1.0.26.\n",
        env!("GEN_RUSTC_VERSION")
    )
    .unwrap();
    emit_ranges(&mut out, "xid_start_table", "Unicode XID_Start (unicode-ident).", &ranges(unicode_ident::is_xid_start));
    emit_ranges(&mut out, "xid_continue_table", "Unicode XID_Continue (unicode-ident).", &ranges(unicode_ident::is_xid_continue));
    emit_ranges(&mut out, "alphanumeric_table", "Rust `char::is_alphanumeric`.", &ranges(char::is_alphanumeric));
    emit_ranges(&mut out, "lowercase_table", "Rust `char::is_lowercase`.", &ranges(char::is_lowercase));
    emit_ranges(&mut out, "uppercase_table", "Rust `char::is_uppercase`.", &ranges(char::is_uppercase));
    emit_ranges(
        &mut out,
        "escape_debug_table",
        "Chars that Rust's `char::escape_debug` renders as `\\u{..}` (not printable or grapheme-extending).",
        &ranges(|c| {
            let e: String = c.escape_debug().collect();
            e.starts_with("\\u{")
        }),
    );
    emit_mapping(&mut out, "lower_map", "Rust `char::to_lowercase`", |c| c.to_lowercase().collect());
    emit_mapping(&mut out, "upper_map", "Rust `char::to_uppercase`", |c| c.to_uppercase().collect());
    print!("{out}");
}
