//! Differential-test oracle: emits MoonBit test files whose expected values are
//! computed by the real Rust crates that upstream typify depends on.
//!
//! Usage: oracle heck > internal/heck/oracle_test.mbt

use heck::{ToKebabCase, ToPascalCase, ToSnakeCase};

/// Tiny deterministic PRNG (splitmix64) so regenerated files are stable.
struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E3779B97F4A7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
        z ^ (z >> 31)
    }
    fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }
}

/// Characters that exercise heck's word-boundary logic and Unicode handling.
const ALPHABET: &[char] = &[
    'a', 'b', 'x', 'y', 'z', 'A', 'B', 'X', 'Y', 'Z', '0', '1', '9', '_', '-', ' ', '.', '/',
    ':', '\'', '+', '$', '@', 'é', 'É', 'ß', 'Σ', 'σ', 'ς', 'İ', 'ı', 'ﬃ', 'Ǆ', 'ǅ', 'ǆ',
    '中', '文', '٣', 'Ⅻ', '😀', '\u{301}', 'ǈ', 'ᾈ',
];

fn random_strings(rng: &mut Rng, count: usize) -> Vec<String> {
    let mut out = Vec::new();
    for _ in 0..count {
        let len = rng.below(12) as usize;
        let s: String = (0..len)
            .map(|_| ALPHABET[rng.below(ALPHABET.len() as u64) as usize])
            .collect();
        out.push(s);
    }
    out
}

fn mbt_string(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            ' '..='~' if c != '"' && c != '\\' => out.push(c),
            _ => out.push_str(&format!("\\u{{{:X}}}", c as u32)),
        }
    }
    out.push('"');
    out
}

fn heck_cases() {
    let mut rng = Rng(0x7479_7069_6679);
    let inputs = random_strings(&mut rng, 600);
    println!("// Code generated by scripts/oracle (heck 0.5.0); DO NOT EDIT.\n");
    println!("///|\nlet oracle_cases : Array[(String, String, String, String)] = [");
    for s in &inputs {
        println!(
            "  ({}, {}, {}, {}),",
            mbt_string(s),
            mbt_string(&s.to_pascal_case()),
            mbt_string(&s.to_snake_case()),
            mbt_string(&s.to_kebab_case())
        );
    }
    println!("]\n");
    println!(
        "///|\ntest \"differential: heck 0.5.0\" {{\n  for case in oracle_cases {{\n    let (input, pascal, snake, kebab) = case\n    assert_eq(@heck.to_pascal_case(input), pascal, msg=\"pascal \\{{input}}\")\n    assert_eq(@heck.to_snake_case(input), snake, msg=\"snake \\{{input}}\")\n    assert_eq(@heck.to_kebab_case(input), kebab, msg=\"kebab \\{{input}}\")\n  }}\n}}"
    );
}

fn main() {
    match std::env::args().nth(1).as_deref() {
        Some("heck") => heck_cases(),
        other => panic!("unknown oracle {other:?}"),
    }
}
