//! Differential-test oracle: emits MoonBit test files whose expected values are
//! computed by the real Rust crates that upstream typify depends on.
//!
//! Usage: oracle heck > internal/heck/oracle_test.mbt

use heck::{ToKebabCase, ToPascalCase, ToSnakeCase};

/// Tiny deterministic PRNG (splitmix64) so regenerated files are stable.
struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E3779B97F4A7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
        z ^ (z >> 31)
    }
    fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }
}

/// Characters that exercise heck's word-boundary logic and Unicode handling.
const ALPHABET: &[char] = &[
    'a', 'b', 'x', 'y', 'z', 'A', 'B', 'X', 'Y', 'Z', '0', '1', '9', '_', '-', ' ', '.', '/',
    ':', '\'', '+', '$', '@', 'é', 'É', 'ß', 'Σ', 'σ', 'ς', 'İ', 'ı', 'ﬃ', 'Ǆ', 'ǅ', 'ǆ',
    '中', '文', '٣', 'Ⅻ', '😀', '\u{301}', 'ǈ', 'ᾈ',
];

fn random_strings(rng: &mut Rng, count: usize) -> Vec<String> {
    let mut out = Vec::new();
    for _ in 0..count {
        let len = rng.below(12) as usize;
        let s: String = (0..len)
            .map(|_| ALPHABET[rng.below(ALPHABET.len() as u64) as usize])
            .collect();
        out.push(s);
    }
    out
}

fn mbt_string(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            ' '..='~' if c != '"' && c != '\\' => out.push(c),
            _ => out.push_str(&format!("\\u{{{:X}}}", c as u32)),
        }
    }
    out.push('"');
    out
}

fn heck_cases() {
    let mut rng = Rng(0x7479_7069_6679);
    let inputs = random_strings(&mut rng, 600);
    println!("// Code generated by scripts/oracle (heck 0.5.0); DO NOT EDIT.\n");
    println!("///|\nlet oracle_cases : Array[(String, String, String, String)] = [");
    for s in &inputs {
        println!(
            "  ({}, {}, {}, {}),",
            mbt_string(s),
            mbt_string(&s.to_pascal_case()),
            mbt_string(&s.to_snake_case()),
            mbt_string(&s.to_kebab_case())
        );
    }
    println!("]\n");
    println!(
        "///|\ntest \"differential: heck 0.5.0\" {{\n  for case in oracle_cases {{\n    let (input, pascal, snake, kebab) = case\n    assert_eq(@heck.to_pascal_case(input), pascal, msg=\"pascal \\{{input}}\")\n    assert_eq(@heck.to_snake_case(input), snake, msg=\"snake \\{{input}}\")\n    assert_eq(@heck.to_kebab_case(input), kebab, msg=\"kebab \\{{input}}\")\n  }}\n}}"
    );
}

fn random_number(rng: &mut Rng) -> String {
    let mut s = String::new();
    if rng.below(3) == 0 {
        s.push('-');
    }
    match rng.below(10) {
        0 => s.push('0'),
        1 => s.push_str("00"),
        _ => {
            let len = 1 + rng.below(24);
            s.push(char::from(b'1' + rng.below(9) as u8));
            for _ in 1..len {
                s.push(char::from(b'0' + rng.below(10) as u8));
            }
        }
    }
    if rng.below(3) == 0 {
        s.push('.');
        for _ in 0..rng.below(20) {
            s.push(char::from(b'0' + rng.below(10) as u8));
        }
    }
    if rng.below(3) == 0 {
        s.push(if rng.below(2) == 0 { 'e' } else { 'E' });
        match rng.below(3) {
            0 => s.push('+'),
            1 => s.push('-'),
            _ => {}
        }
        let digits = rng.below(4);
        for _ in 0..digits {
            s.push(char::from(b'0' + rng.below(10) as u8));
        }
        if rng.below(10) == 0 {
            s.push_str("99999999999");
        }
    }
    s
}

fn random_string_lit(rng: &mut Rng) -> String {
    const PIECES: &[&str] = &[
        "a", "Z", " ", "\\\"", "\\\\", "\\/", "\\b", "\\f", "\\n", "\\r", "\\t", "\\u0041",
        "\\u00e9", "\\ud83d\\ude00", "\\ud83d", "\\ude00", "\\uZZZZ", "\\x", "é", "中", "😀",
        "\u{1}", "\u{7f}", "\\u0000",
    ];
    let mut s = String::from("\"");
    for _ in 0..rng.below(6) {
        s.push_str(PIECES[rng.below(PIECES.len() as u64) as usize]);
    }
    if rng.below(20) != 0 {
        s.push('"');
    }
    s
}

fn random_json(rng: &mut Rng, depth: u32) -> String {
    let ws = |rng: &mut Rng| -> &'static str {
        [" ", "", "", "\n", "\t", "\r "][rng.below(6) as usize]
    };
    let pick = if depth > 3 { rng.below(6) } else { rng.below(9) };
    match pick {
        0 => ["null", "true", "false", "nul", "tru", "True"][rng.below(6) as usize].to_string(),
        1 | 2 => random_number(rng),
        3 | 4 | 5 => random_string_lit(rng),
        6 | 7 => {
            let n = rng.below(4);
            let mut s = String::from("[");
            for i in 0..n {
                if i > 0 {
                    s.push(',');
                }
                s.push_str(ws(rng));
                s.push_str(&random_json(rng, depth + 1));
            }
            if rng.below(15) == 0 {
                s.push(',');
            }
            s.push_str(ws(rng));
            if rng.below(20) != 0 {
                s.push(']');
            }
            s
        }
        _ => {
            let n = rng.below(4);
            let mut s = String::from("{");
            for i in 0..n {
                if i > 0 {
                    s.push(',');
                }
                const KEYS: &[&str] = &["\"a\"", "\"b\"", "\"aa\"", "\"\\u00e9\"", "\"😀\"", "\"\"", "1"];
                s.push_str(KEYS[rng.below(KEYS.len() as u64) as usize]);
                s.push_str(ws(rng));
                if rng.below(20) != 0 {
                    s.push(':');
                }
                s.push_str(&random_json(rng, depth + 1));
            }
            s.push_str(ws(rng));
            if rng.below(20) != 0 {
                s.push('}');
            }
            s
        }
    }
}

fn json_cases() {
    let mut rng = Rng(0x6a73_6f6e);
    println!("// Code generated by scripts/oracle (serde_json 1.0.151); DO NOT EDIT.\n");
    println!("///|\n/// (input, compact output or \"ERR: <serde_json error>\", pretty output)");
    println!("let parse_cases : Array[(String, String, String)] = [");
    let mut inputs: Vec<String> = Vec::new();
    for _ in 0..1500 {
        let mut s = random_json(&mut rng, 0);
        if rng.below(25) == 0 {
            s.push_str(" x");
        }
        if rng.below(10) == 0 {
            s = format!("  {s}\n ");
        }
        inputs.push(s);
    }
    inputs.push("[".repeat(127) + &"]".repeat(127));
    inputs.push("[".repeat(128) + &"]".repeat(128));
    inputs.push("{\"a\":1,\"a\":2}".to_string());
    for extra in [
        "", " ", "[", "[1,", "{", r#"{"a""#, r#"{"a":"#, r#"{"a":1,"#, "01", "-", "-a", "1.", "1.e5",
        "1e", "1e+", r#""\ud800""#, r#""\ud800A""#, r#""\udc00""#, "\"\u{e9}\u{1}\"",
        "\n\n  [1, 2,\n  x]", "\"\u{4e2d}\u{6587}\" x", "[1] x", "1e999", "-1e999", "1e-999",
        "0e999999999999", "[1 2]", r#"{"a" 1}"#, "{1:2}", r#"{"a":1 "b":2}"#, "nulx", "tru",
        r#""abc"#, r#""\q""#, "18446744073709551616", "-9223372036854775809",
        "-9223372036854775808", "123456789012345678901234567890.5e-10", "[\"\u{e9}\", x]",
    ] {
        inputs.push(extra.to_string());
    }
    for s in &inputs {
        let (compact, pretty) = match serde_json::from_str::<serde_json::Value>(s) {
            Ok(v) => (v.to_string(), serde_json::to_string_pretty(&v).unwrap()),
            Err(e) => (format!("ERR: {e}"), String::new()),
        };
        println!("  ({}, {}, {}),", mbt_string(s), mbt_string(&compact), mbt_string(&pretty));
    }
    println!("]\n");
    println!("///|\n/// (f64 bits, serde_json/ryu text)");
    println!("let float_cases : Array[(UInt64, String)] = [");
    let mut specials: Vec<f64> = vec![
        0.0, -0.0, 1.0, -1.0, 0.1, 1e15, 1e16, 1e17, 1e21, 1e22, 1e-5, 1e-6, 1e-7, 123456.789,
        f64::MIN_POSITIVE, f64::MAX, f64::MIN, 5e-324, 9007199254740993.0, 1.5e300, 2.5e-300,
    ];
    for _ in 0..2000 {
        let bits = rng.next();
        let f = f64::from_bits(bits);
        if f.is_finite() {
            specials.push(f);
        }
        // Also "nice" decimal values.
        let n = (rng.below(1_000_000) as f64) / 10f64.powi(rng.below(12) as i32);
        specials.push(n * 10f64.powi(rng.below(40) as i32 - 10));
    }
    for f in specials {
        let text = serde_json::Number::from_f64(f).unwrap().to_string();
        println!("  ({}UL, {}),", f.to_bits(), mbt_string(&text));
    }
    println!("]\n");
    println!(r#"///|
test "differential: serde_json parse and print" {{
  for case in parse_cases {{
    let (input, compact, pretty) = case
    let (got_compact, got_pretty) = try @serde_json.parse(input) catch {{
      e => ("ERR: \{{e}}", "")
    }} noraise {{
      v => (v.to_string(), v.to_string_pretty())
    }}
    assert_eq(got_compact, compact, msg="compact: \{{input}}")
    assert_eq(got_pretty, pretty, msg="pretty: \{{input}}")
  }}
}}

///|
test "differential: ryu float formatting" {{
  for case in float_cases {{
    let (bits, text) = case
    let d = bits.reinterpret_as_double()
    assert_eq(@serde_json.format_f64(d), text, msg="bits \{{bits}}")
  }}
}}"#);
}

fn main() {
    match std::env::args().nth(1).as_deref() {
        Some("heck") => heck_cases(),
        Some("json") => json_cases(),
        Some("f64") => {
            for text in std::env::args().skip(2) {
                let v: serde_json::Value = serde_json::from_str(&text).unwrap();
                let f = v.as_f64().unwrap();
                println!("{text} -> {f:?} (exact parse {:?})", text.parse::<f64>().unwrap());
            }
        }
        other => panic!("unknown oracle {other:?}"),
    }
}
