//! Differential-test oracle: emits MoonBit test files whose expected values are
//! computed by the real Rust crates that upstream typify depends on.
//!
//! Usage: oracle heck > internal/heck/oracle_test.mbt

use heck::{ToKebabCase, ToPascalCase, ToSnakeCase};

/// Tiny deterministic PRNG (splitmix64) so regenerated files are stable.
struct Rng(u64);
impl Rng {
    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E3779B97F4A7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D049BB133111EB);
        z ^ (z >> 31)
    }
    fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }
}

/// Characters that exercise heck's word-boundary logic and Unicode handling.
const ALPHABET: &[char] = &[
    'a', 'b', 'x', 'y', 'z', 'A', 'B', 'X', 'Y', 'Z', '0', '1', '9', '_', '-', ' ', '.', '/',
    ':', '\'', '+', '$', '@', 'é', 'É', 'ß', 'Σ', 'σ', 'ς', 'İ', 'ı', 'ﬃ', 'Ǆ', 'ǅ', 'ǆ',
    '中', '文', '٣', 'Ⅻ', '😀', '\u{301}', 'ǈ', 'ᾈ',
];

fn random_strings(rng: &mut Rng, count: usize) -> Vec<String> {
    let mut out = Vec::new();
    for _ in 0..count {
        let len = rng.below(12) as usize;
        let s: String = (0..len)
            .map(|_| ALPHABET[rng.below(ALPHABET.len() as u64) as usize])
            .collect();
        out.push(s);
    }
    out
}

fn mbt_string(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            ' '..='~' if c != '"' && c != '\\' => out.push(c),
            _ => out.push_str(&format!("\\u{{{:X}}}", c as u32)),
        }
    }
    out.push('"');
    out
}

fn heck_cases() {
    let mut rng = Rng(0x7479_7069_6679);
    let inputs = random_strings(&mut rng, 600);
    println!("// Code generated by scripts/oracle (heck 0.5.0); DO NOT EDIT.\n");
    println!("///|\nlet oracle_cases : Array[(String, String, String, String)] = [");
    for s in &inputs {
        println!(
            "  ({}, {}, {}, {}),",
            mbt_string(s),
            mbt_string(&s.to_pascal_case()),
            mbt_string(&s.to_snake_case()),
            mbt_string(&s.to_kebab_case())
        );
    }
    println!("]\n");
    println!(
        "///|\ntest \"differential: heck 0.5.0\" {{\n  for case in oracle_cases {{\n    let (input, pascal, snake, kebab) = case\n    assert_eq(@heck.to_pascal_case(input), pascal, msg=\"pascal \\{{input}}\")\n    assert_eq(@heck.to_snake_case(input), snake, msg=\"snake \\{{input}}\")\n    assert_eq(@heck.to_kebab_case(input), kebab, msg=\"kebab \\{{input}}\")\n  }}\n}}"
    );
}

fn random_number(rng: &mut Rng) -> String {
    let mut s = String::new();
    if rng.below(3) == 0 {
        s.push('-');
    }
    match rng.below(10) {
        0 => s.push('0'),
        1 => s.push_str("00"),
        _ => {
            let len = 1 + rng.below(24);
            s.push(char::from(b'1' + rng.below(9) as u8));
            for _ in 1..len {
                s.push(char::from(b'0' + rng.below(10) as u8));
            }
        }
    }
    if rng.below(3) == 0 {
        s.push('.');
        for _ in 0..rng.below(20) {
            s.push(char::from(b'0' + rng.below(10) as u8));
        }
    }
    if rng.below(3) == 0 {
        s.push(if rng.below(2) == 0 { 'e' } else { 'E' });
        match rng.below(3) {
            0 => s.push('+'),
            1 => s.push('-'),
            _ => {}
        }
        let digits = rng.below(4);
        for _ in 0..digits {
            s.push(char::from(b'0' + rng.below(10) as u8));
        }
        if rng.below(10) == 0 {
            s.push_str("99999999999");
        }
    }
    s
}

fn random_string_lit(rng: &mut Rng) -> String {
    const PIECES: &[&str] = &[
        "a", "Z", " ", "\\\"", "\\\\", "\\/", "\\b", "\\f", "\\n", "\\r", "\\t", "\\u0041",
        "\\u00e9", "\\ud83d\\ude00", "\\ud83d", "\\ude00", "\\uZZZZ", "\\x", "é", "中", "😀",
        "\u{1}", "\u{7f}", "\\u0000",
    ];
    let mut s = String::from("\"");
    for _ in 0..rng.below(6) {
        s.push_str(PIECES[rng.below(PIECES.len() as u64) as usize]);
    }
    if rng.below(20) != 0 {
        s.push('"');
    }
    s
}

fn random_json(rng: &mut Rng, depth: u32) -> String {
    let ws = |rng: &mut Rng| -> &'static str {
        [" ", "", "", "\n", "\t", "\r "][rng.below(6) as usize]
    };
    let pick = if depth > 3 { rng.below(6) } else { rng.below(9) };
    match pick {
        0 => ["null", "true", "false", "nul", "tru", "True"][rng.below(6) as usize].to_string(),
        1 | 2 => random_number(rng),
        3 | 4 | 5 => random_string_lit(rng),
        6 | 7 => {
            let n = rng.below(4);
            let mut s = String::from("[");
            for i in 0..n {
                if i > 0 {
                    s.push(',');
                }
                s.push_str(ws(rng));
                s.push_str(&random_json(rng, depth + 1));
            }
            if rng.below(15) == 0 {
                s.push(',');
            }
            s.push_str(ws(rng));
            if rng.below(20) != 0 {
                s.push(']');
            }
            s
        }
        _ => {
            let n = rng.below(4);
            let mut s = String::from("{");
            for i in 0..n {
                if i > 0 {
                    s.push(',');
                }
                const KEYS: &[&str] = &["\"a\"", "\"b\"", "\"aa\"", "\"\\u00e9\"", "\"😀\"", "\"\"", "1"];
                s.push_str(KEYS[rng.below(KEYS.len() as u64) as usize]);
                s.push_str(ws(rng));
                if rng.below(20) != 0 {
                    s.push(':');
                }
                s.push_str(&random_json(rng, depth + 1));
            }
            s.push_str(ws(rng));
            if rng.below(20) != 0 {
                s.push('}');
            }
            s
        }
    }
}

fn json_cases() {
    let mut rng = Rng(0x6a73_6f6e);
    println!("// Code generated by scripts/oracle (serde_json 1.0.151); DO NOT EDIT.\n");
    println!("///|\n/// (input, compact output or \"ERR: <serde_json error>\", pretty output)");
    println!("let parse_cases : Array[(String, String, String)] = [");
    let mut inputs: Vec<String> = Vec::new();
    for _ in 0..1500 {
        let mut s = random_json(&mut rng, 0);
        if rng.below(25) == 0 {
            s.push_str(" x");
        }
        if rng.below(10) == 0 {
            s = format!("  {s}\n ");
        }
        inputs.push(s);
    }
    inputs.push("[".repeat(127) + &"]".repeat(127));
    inputs.push("[".repeat(128) + &"]".repeat(128));
    inputs.push("{\"a\":1,\"a\":2}".to_string());
    for extra in [
        "", " ", "[", "[1,", "{", r#"{"a""#, r#"{"a":"#, r#"{"a":1,"#, "01", "-", "-a", "1.", "1.e5",
        "1e", "1e+", r#""\ud800""#, r#""\ud800A""#, r#""\udc00""#, "\"\u{e9}\u{1}\"",
        "\n\n  [1, 2,\n  x]", "\"\u{4e2d}\u{6587}\" x", "[1] x", "1e999", "-1e999", "1e-999",
        "0e999999999999", "[1 2]", r#"{"a" 1}"#, "{1:2}", r#"{"a":1 "b":2}"#, "nulx", "tru",
        r#""abc"#, r#""\q""#, "18446744073709551616", "-9223372036854775809",
        "-9223372036854775808", "123456789012345678901234567890.5e-10", "[\"\u{e9}\", x]",
    ] {
        inputs.push(extra.to_string());
    }
    for s in &inputs {
        let (compact, pretty) = match serde_json::from_str::<serde_json::Value>(s) {
            Ok(v) => (v.to_string(), serde_json::to_string_pretty(&v).unwrap()),
            Err(e) => (format!("ERR: {e}"), String::new()),
        };
        println!("  ({}, {}, {}),", mbt_string(s), mbt_string(&compact), mbt_string(&pretty));
    }
    println!("]\n");
    println!("///|\n/// (f64 bits, serde_json/ryu text)");
    println!("let float_cases : Array[(UInt64, String)] = [");
    let mut specials: Vec<f64> = vec![
        0.0, -0.0, 1.0, -1.0, 0.1, 1e15, 1e16, 1e17, 1e21, 1e22, 1e-5, 1e-6, 1e-7, 123456.789,
        f64::MIN_POSITIVE, f64::MAX, f64::MIN, 5e-324, 9007199254740993.0, 1.5e300, 2.5e-300,
    ];
    for _ in 0..2000 {
        let bits = rng.next();
        let f = f64::from_bits(bits);
        if f.is_finite() {
            specials.push(f);
        }
        // Also "nice" decimal values.
        let n = (rng.below(1_000_000) as f64) / 10f64.powi(rng.below(12) as i32);
        specials.push(n * 10f64.powi(rng.below(40) as i32 - 10));
    }
    for f in specials {
        let text = serde_json::Number::from_f64(f).unwrap().to_string();
        println!("  ({}UL, {}),", f.to_bits(), mbt_string(&text));
    }
    println!("]\n");
    println!(r#"///|
test "differential: serde_json parse and print" {{
  for case in parse_cases {{
    let (input, compact, pretty) = case
    let (got_compact, got_pretty) = try @serde_json.parse(input) catch {{
      e => ("ERR: \{{e}}", "")
    }} noraise {{
      v => (v.to_string(), v.to_string_pretty())
    }}
    assert_eq(got_compact, compact, msg="compact: \{{input}}")
    assert_eq(got_pretty, pretty, msg="pretty: \{{input}}")
  }}
}}

///|
test "differential: ryu float formatting" {{
  for case in float_cases {{
    let (bits, text) = case
    let d = bits.reinterpret_as_double()
    assert_eq(@serde_json.format_f64(d), text, msg="bits \{{bits}}")
  }}
}}"#);
}


fn random_pattern(rng: &mut Rng, depth: u32) -> String {
    const ATOMS: &[&str] = &[
        "a", "b", "c", "x", "Z", "0", "9", ".", "\\d", "\\D", "\\w", "\\W", "\\s", "\\S", "\\b",
        "\\B", "^", "$", "[a-c]", "[^a]", "[a-]", "[\\d.]", "[\\w-z]", "[]", "[^]", "[\\b]", "\\.",
        "\\\\", "\\-", "\\/", "\\u0061", "\\u{62}", "\\x41", "\\x4", "\\0", "\\01", "\\1", "\\2",
        "\\12", "\\8", "\\k", "\\k<n>", "\\cA", "\\c1", "\\q", "é", "中", "😀", " ", "-", "_",
        "{", "}", "]", "{2}", "a{", "\\u{110000}", "\\ud83d\\ude00", "\\ud83d", "[z-a]", "(", ")",
        "|", "*", "+", "?", "[\\s]", "[\\c_]", "\\n", "\\t", "(?i:a)", "(?i:[a-c])", "(?-i:A)",
        "(?m:^a$)", "(?s:.)", "(?ii:a)", "(?x:a)", "(?:)", "()", "(?<n>a)", "(?<1>a)", "[[]", "\\",
    ];
    let mut s = String::new();
    let n = 1 + rng.below(5);
    for _ in 0..n {
        let pick = rng.below(if depth > 2 { 10 } else { 14 });
        match pick {
            0..=8 => s.push_str(ATOMS[rng.below(ATOMS.len() as u64) as usize]),
            9 => {
                const Q: &[&str] = &["*", "+", "?", "*?", "+?", "??", "{2}", "{1,3}", "{2,}", "{3,1}", "{,2}", "{0}"];
                s.push_str(Q[rng.below(Q.len() as u64) as usize]);
            }
            10 => {
                const G: &[&str] = &["(", "(?:", "(?=", "(?!", "(?<=", "(?<!", "(?<n>", "(?i:"];
                s.push_str(G[rng.below(G.len() as u64) as usize]);
                s.push_str(&random_pattern(rng, depth + 1));
                if rng.below(15) != 0 {
                    s.push(')');
                }
            }
            11 => {
                s.push_str(&random_pattern(rng, depth + 1));
                s.push('|');
                s.push_str(&random_pattern(rng, depth + 1));
            }
            _ => {
                s.push('(');
                s.push_str(&random_pattern(rng, depth + 1));
                s.push(')');
                s.push_str(["\\1", "\\2", "*", "+", ""][rng.below(5) as usize]);
            }
        }
    }
    s
}

fn random_subject(rng: &mut Rng) -> String {
    const CH: &[&str] = &["a", "b", "c", "x", "A", "Z", "0", "9", " ", "-", "_", ".", "\n", "é", "É", "中", "😀", "\u{2028}", "k", "\u{8}"];
    let n = rng.below(8);
    (0..n).map(|_| CH[rng.below(CH.len() as u64) as usize]).collect()
}

fn utf16_offset(s: &str, byte: usize) -> usize {
    s[..byte].encode_utf16().count()
}

fn regex_cases() {
    let mut rng = Rng(0x7265_6765_78);
    println!("// Code generated by scripts/oracle (regress 0.12.0); DO NOT EDIT.\n");
    println!("///|\n/// (pattern, subject, expected: \"ERR: <text>\" | \"NONE\" | \"start..end\" in UTF-16)");
    println!("let regex_cases : Array[(String, String, String)] = [");
    let mut patterns: Vec<String> = (0..2500).map(|_| random_pattern(&mut rng, 0)).collect();
    for p in [
        "^[a-zA-Z0-9_]+$", "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$", "(?=a)(?=b)", "(?=.*a)(?=.*b)",
        "^(?!.*\\.\\.)[a-z.]+$", "(?<=a)b", "(?<!a)b", "(a*)*b", "(a|ab)(c|bcd)(d*)", "^(?:(a)|b)*$",
        "(z)((a+)?(b+)?(c))*", "^\\p{L}+$", "[\\u{61}-\\u{63}]", "^.$", "\\u{1F600}", "(?<a>x)|(?<a>y)",
        "(?<a>x)(?<a>y)", "\\k<a>(?<a>x)", "(?<a>.)\\k<a>", "a{2,3}?", "^\\s*$", "[\\w\\-]+", "\\cj",
        "(?i:straße)", "(?i:[k])", "(?i:σ)", "(?i:\\w)", "x{", "x{1", "x{1,", "{1}", "a**", "a{3,1}",
    ] {
        patterns.push(p.to_string());
    }
    for p in &patterns {
        let subjects: Vec<String> = (0..4).map(|_| random_subject(&mut rng)).chain([
            "abc".to_string(), "ab".to_string(), "".to_string(), "xyz ab_c-9".to_string(),
        ]).collect();
        match regress::Regex::new(p) {
            Err(e) => {
                println!("  ({}, \"\", {}),", mbt_string(p), mbt_string(&format!("ERR: {e}")));
            }
            Ok(re) => {
                for subj in subjects {
                    let out = match re.find(&subj) {
                        None => "NONE".to_string(),
                        Some(m) => format!(
                            "{}..{}",
                            utf16_offset(&subj, m.start()),
                            utf16_offset(&subj, m.end())
                        ),
                    };
                    println!("  ({}, {}, {}),", mbt_string(p), mbt_string(&subj), mbt_string(&out));
                }
            }
        }
    }
    println!("]\n");
    println!(r#"///|
test "differential: regress 0.12.0" {{
  let failures = []
  for case in regex_cases {{
    let (pattern, subject, expected) = case
    let got = try @regex.Regex::new(pattern) catch {{
      e => "ERR: \{{e}}"
    }} noraise {{
      re =>
        match re.find(subject) {{
          None => "NONE"
          Some(m) => "\{{m.start}}..\{{m.end}}"
        }}
    }}
    if got != expected {{
      failures.push("\{{pattern.escape()}} on \{{subject.escape()}}: want \{{expected}}, got \{{got}}")
    }}
  }}
  if !failures.is_empty() {{
    let shown = failures.length().min(20)
    let head = failures[:shown].to_owned().join("\n")
    fail("\{{failures.length()}} mismatches:\n\{{head}}")
  }}
}}"#);
}


fn random_value(rng: &mut Rng, depth: u32) -> String {
    match rng.below(if depth > 1 { 7 } else { 9 }) {
        0 => "null".into(),
        1 => ["true", "false"][rng.below(2) as usize].into(),
        2 => ["0", "1", "5", "-1", "1.0", "2.5", "4294967296", "1e2"][rng.below(8) as usize].into(),
        3 => ["\"a\"", "\"string\"", "\"integer\"", "\"#/definitions/A\"", "\"\""][rng.below(5) as usize].into(),
        4 | 5 | 6 => random_schema(rng, depth + 1),
        7 => {
            let n = rng.below(3);
            let items: Vec<String> = (0..n).map(|_| random_value(rng, depth + 1)).collect();
            format!("[{}]", items.join(","))
        }
        _ => {
            let n = rng.below(3);
            let items: Vec<String> = (0..n)
                .map(|i| format!("\"k{i}\":{}", random_value(rng, depth + 1)))
                .collect();
            format!("{{{}}}", items.join(","))
        }
    }
}

fn random_schema(rng: &mut Rng, depth: u32) -> String {
    if depth > 3 {
        return ["true", "false", "{}"][rng.below(3) as usize].into();
    }
    const KEYS: &[&str] = &[
        "$id", "title", "description", "default", "deprecated", "readOnly", "writeOnly", "examples",
        "type", "format", "enum", "const", "allOf", "anyOf", "oneOf", "not", "if", "then", "else",
        "multipleOf", "maximum", "exclusiveMaximum", "minimum", "exclusiveMinimum", "maxLength",
        "minLength", "pattern", "items", "additionalItems", "maxItems", "minItems", "uniqueItems",
        "contains", "maxProperties", "minProperties", "required", "properties", "patternProperties",
        "additionalProperties", "propertyNames", "$ref", "x-ext", "$comment", "definitions",
    ];
    let n = rng.below(5);
    let mut used = std::collections::BTreeSet::new();
    let mut parts = Vec::new();
    for _ in 0..n {
        let k = KEYS[rng.below(KEYS.len() as u64) as usize];
        if !used.insert(k) {
            continue;
        }
        let good = rng.below(4) != 0;
        let v = if !good {
            random_value(rng, depth + 1)
        } else {
            match k {
                "$id" | "title" | "description" | "format" | "pattern" | "$ref" => "\"s\"".to_string(),
                "deprecated" | "readOnly" | "writeOnly" | "uniqueItems" => "true".into(),
                "examples" | "enum" => "[1,\"a\",null]".into(),
                "type" => ["\"string\"", "[\"string\",\"null\"]", "\"integer\""][rng.below(3) as usize].into(),
                "allOf" | "anyOf" | "oneOf" => format!("[{}]", random_schema(rng, depth + 1)),
                "multipleOf" | "maximum" | "exclusiveMaximum" | "minimum" | "exclusiveMinimum" => "3".into(),
                "maxLength" | "minLength" | "maxItems" | "minItems" | "maxProperties" | "minProperties" => "2".into(),
                "required" => "[\"b\",\"a\",\"b\"]".into(),
                "properties" | "patternProperties" | "definitions" => {
                    format!("{{\"b\":{},\"a\":{}}}", random_schema(rng, depth + 1), random_schema(rng, depth + 1))
                }
                "items" => {
                    if rng.below(2) == 0 {
                        random_schema(rng, depth + 1)
                    } else {
                        format!("[{}]", random_schema(rng, depth + 1))
                    }
                }
                _ => random_schema(rng, depth + 1),
            }
        };
        parts.push(format!("\"{k}\":{v}"));
    }
    format!("{{{}}}", parts.join(","))
}

fn schemars_cases() {
    // 1. Fixture files: expected serialization written next to the fixtures.
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
    let out_dir = root.join("tests/oracle/schemars");
    std::fs::create_dir_all(&out_dir).unwrap();
    let mut files: Vec<std::path::PathBuf> = std::fs::read_dir(root.join("tests/upstream/schemas"))
        .unwrap()
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().map_or(false, |e| e == "json"))
        .collect();
    files.push(root.join("tests/upstream/impl/github.json"));
    files.push(root.join("tests/upstream/impl/vega.json"));
    files.sort();
    for f in &files {
        let text = std::fs::read_to_string(f).unwrap();
        let rs: schemars::schema::RootSchema = serde_json::from_str(&text).unwrap();
        let v = serde_json::to_value(&rs).unwrap();
        std::fs::write(out_dir.join(f.file_name().unwrap()), v.to_string()).unwrap();
    }
    // 2. Random documents.
    let mut rng = Rng(0x7363_6865_6d61);
    println!("// Code generated by scripts/oracle (schemars 0.8.22); DO NOT EDIT.\n");
    println!("///|\n/// (input, serialized RootSchema or \"ERR\")");
    println!("let schemars_cases : Array[(String, String)] = [");
    for _ in 0..1500 {
        let doc = random_schema(&mut rng, 0);
        let out = match serde_json::from_str::<schemars::schema::RootSchema>(&doc) {
            Ok(rs) => serde_json::to_value(&rs).unwrap().to_string(),
            Err(_) => "ERR".to_string(),
        };
        println!("  ({}, {}),", mbt_string(&doc), mbt_string(&out));
    }
    println!("]\n");
    let names: Vec<String> = files
        .iter()
        .map(|f| mbt_string(f.file_name().unwrap().to_str().unwrap()))
        .collect();
    println!("///|\nlet schemars_fixture_names : Array[String] = [{}]\n", names.join(", "));
    println!(r#"///|
test "differential: schemars 0.8.22 on random documents" {{
  let failures = []
  for case in schemars_cases {{
    let (input, expected) = case
    let got = try @schema.RootSchema::from_json_str(input) catch {{
      _ => "ERR"
    }} noraise {{
      root => root.to_value().to_string()
    }}
    if got != expected {{
      failures.push("\{{input}}\n  want: \{{expected}}\n  got:  \{{got}}")
    }}
  }}
  if !failures.is_empty() {{
    let shown = failures.length().min(10)
    let head = failures[:shown].to_owned().join("\n")
    fail("\{{failures.length()}} mismatches:\n\{{head}}")
  }}
}}

///|
test "differential: schemars 0.8.22 on upstream fixtures" {{
  for name in schemars_fixture_names {{
    let dir = if name is ("github.json" | "vega.json") {{ "impl" }} else {{ "schemas" }}
    let input = @fs.read_file_to_string("tests/upstream/\{{dir}}/\{{name}}")
    let expected = @fs.read_file_to_string("tests/oracle/schemars/\{{name}}")
    let got = @schema.RootSchema::from_json_str(input).to_value().to_string()
    assert_true(got == expected, msg="fixture \{{name}}")
  }}
}}"#);
}

fn f32_cases() {
    let mut rng = Rng(0x5eed_f32f);
    println!("// Generated by scripts/oracle (f32 mode); DO NOT EDIT.\n");
    println!("///|\n/// (f32 bits, serde_json::to_string(&f32))");
    println!("let f32_cases : Array[(UInt, String)] = [");
    let mut values: Vec<f32> = vec![
        0.0, -0.0, 1.0, -1.0, 0.1, 0.3, 1e-6, 1e-7, 1e12, 1e13, 1e-5, 123456789.125,
        16777216.0, 16777217.0, f32::MIN_POSITIVE, f32::MAX, f32::MIN, f32::EPSILON,
        f32::from_bits(1), f32::from_bits(0x007f_ffff), 3.4e38, 1e-40, 9.999999e12, 1e38,
    ];
    for e in 0..254u32 {
        values.push(f32::from_bits(e << 23));
        values.push(f32::from_bits((e << 23) | 1));
        values.push(f32::from_bits((e << 23) | 0x7f_ffff));
    }
    for _ in 0..3000 {
        let f = f32::from_bits(rng.next() as u32);
        if f.is_finite() {
            values.push(f);
        }
        let n = (rng.below(100_000_000) as f64) / 10f64.powi(rng.below(12) as i32);
        values.push((n * 10f64.powi(rng.below(30) as i32 - 15)) as f32);
        values.push(f32::from_bits((rng.below(8) as u32) << 23 | rng.next() as u32 & 0x7f_ffff));
    }
    for f in values {
        println!("  ({}U, {}),", f.to_bits(), mbt_string(&serde_json::to_string(&f).unwrap()));
    }
    println!("]\n");
    println!(r#"///|
test "differential: zmij f32 formatting" {{
  for case in f32_cases {{
    let (bits, text) = case
    let f = Float::reinterpret_from_uint(bits)
    assert_eq(@serde_json.format_f32(f), text, msg="bits \{{bits}}")
  }}
}}"#);
}

fn main() {
    match std::env::args().nth(1).as_deref() {
        Some("heck") => heck_cases(),
        Some("json") => json_cases(),
        Some("regex") => regex_cases(),
        Some("schemars") => schemars_cases(),
        Some("f32") => f32_cases(),
        Some("f64") => {
            for text in std::env::args().skip(2) {
                let v: serde_json::Value = serde_json::from_str(&text).unwrap();
                let f = v.as_f64().unwrap();
                println!("{text} -> {f:?} (exact parse {:?})", text.parse::<f64>().unwrap());
            }
        }
        other => panic!("unknown oracle {other:?}"),
    }
}
